export const SUPERVISION_LIST_SUMMARY_SELECT = [
  "id",
  "created_at",
  "operation_name",
  "officer_name",
  "type",
  "id_number",
  "officer_phone",
  "weapon_model",
  "weapon_serial",
  "review_post",
  "lugar",
  "status",
  "supervisor_id",
].join(",")

export const SUPERVISION_LIST_SUMMARY_SELECT_STABLE = [
  "id",
  "created_at",
  "operation_name",
  "officer_name",
  "type",
  "id_number",
  "weapon_model",
  "weapon_serial",
  "review_post",
  "lugar",
  "status",
  "supervisor_id",
].join(",")

export const SUPERVISION_DETAIL_SELECT_EXTENDED = [
  "id",
  "created_at",
  "operation_name",
  "officer_name",
  "type",
  "id_number",
  "officer_phone",
  "weapon_model",
  "weapon_serial",
  "review_post",
  "lugar",
  "gps",
  "photos",
  "evidence_bundle",
  "geo_risk",
  "checklist",
  "checklist_reasons",
  "property_details",
  "observations",
  "status",
  "supervisor_id",
].join(",")

export const SUPERVISION_DETAIL_SELECT_STABLE = [
  "id",
  "created_at",
  "operation_name",
  "officer_name",
  "type",
  "id_number",
  "weapon_model",
  "weapon_serial",
  "review_post",
  "lugar",
  "gps",
  "photos",
  "checklist",
  "checklist_reasons",
  "property_details",
  "observations",
  "status",
  "supervisor_id",
].join(",")

export const ROUND_REPORT_GROUPED_SUMMARY_SELECT = [
  "id",
  "created_at",
  "started_at",
  "ended_at",
  "round_id",
  "round_name",
  "post_name",
  "officer_id",
  "officer_name",
  "status",
  "checkpoints_total",
  "checkpoints_completed",
  "notes",
].join(",")

export const ROUND_REPORT_CONTEXT_SELECT_EXTENDED = [
  "id",
  "started_at",
  "ended_at",
  "round_id",
  "round_name",
  "post_name",
  "officer_id",
  "officer_name",
  "supervisor_name",
  "supervisor_id",
  "status",
  "notes",
  "checkpoints_total",
  "checkpoints_completed",
  "created_at",
  "checkpoint_logs",
].join(",")

export const ROUND_REPORT_CONTEXT_SELECT_STABLE = [
  "id",
  "started_at",
  "ended_at",
  "round_id",
  "round_name",
  "post_name",
  "officer_id",
  "officer_name",
  "status",
  "notes",
  "checkpoints_total",
  "checkpoints_completed",
  "created_at",
  "checkpoint_logs",
].join(",")

export const ROUND_REPORT_GROUPED_DETAIL_SELECT = [
  "id",
  "created_at",
  "started_at",
  "ended_at",
  "round_id",
  "round_name",
  "post_name",
  "officer_id",
  "officer_name",
  "status",
  "checkpoints_total",
  "checkpoints_completed",
  "notes",
  "checkpoint_logs",
].join(",")